import CICDTriggerCard from "../components/CICDTriggerCard";
import JenkinsJobCard from "../components/JenkinsJobCard";
import { config } from "../config";

const CICD_JOB_URL = "https://jenkins-qa2.inca.infoblox.com/job/IB_QA_CI_NIOS_CVE_Analyser";

export default function CICDPage() {
  return (
    <div className="space-y-6">
      <section>
        <div className="text-[11px] font-semibold uppercase tracking-wider text-ink-subtle">
          End-to-End Pipeline
        </div>
        <h1 className="mt-1 text-2xl font-semibold tracking-tight">
          CICD Pipeline
        </h1>
        <p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink-muted">
          Triggers the full end-to-end NIOS CVE pipeline on QA2 Jenkins. Builds with a branch parameter
          that comes from either the trigger input below or the default branch generated by the automation scripts.
        </p>
      </section>

      {/* Trigger section */}
      <CICDTriggerCard />

      {/* Live job status */}
      <section className="space-y-3">
        <div className="flex items-center gap-3">
          <h2 className="text-sm font-semibold">Jenkins Job Status</h2>
          <span className="text-[11px] text-ink-subtle">Live data · auto-refresh every {Math.round(config.api.pollIntervalMs / 1000)}s</span>
        </div>
        <JenkinsJobCard
          title="IB_QA_CI_NIOS_CVE_Analyser"
          jenkinsUrl={CICD_JOB_URL}
        />
      </section>
    </div>
  );
}
